server:
  servlet:
    context-path: /realz
  port: 11016
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/architect_practise?useUnicode=true&characterEncoding=utf8&useSSL=false
  liquibase:
    change-log: classpath:/database/init.xml
  redis:
    host: redis
    port: 6379

mybatis-plus:
  mapper-locations: com/practise/realz/mapper/*Mapper.xml

